package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   账户信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_ACCOUNT
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-26 19:47:00
 */
@ApiModel(value = "AfcAccountMo", description = "账户信息")
@JsonInclude(Include.NON_NULL)
public class AfcAccountMo implements Serializable {
    /**
     * Database Column Remarks:
     *   账户ID(账户ID也就是用户ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "账户ID(账户ID也就是用户ID)")
    private Long id;

    /**
     * Database Column Remarks:
     *   余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "余额")
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   最后结算余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.SETTLE_BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "最后结算余额")
    private BigDecimal settleBalance;

    /**
     * Database Column Remarks:
     *   最后结算时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.SETTLE_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "最后结算时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date settleTime;

    /**
     * Database Column Remarks:
     *   提现中总额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.WITHDRAWING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "提现中总额")
    private BigDecimal withdrawing;

    /**
     * Database Column Remarks:
     *   返现金余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.CASHBACK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "返现金余额")
    private BigDecimal cashback;

    /**
     * Database Column Remarks:
     *   返现中的金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.CASHBACKING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "返现中的金额")
    private BigDecimal cashbacking;

    /**
     * Database Column Remarks:
     *   进货保证金
     *               提货时要检查此加盟商的已进货的金额+本次提货的货物成本不能超过此金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.DEPOSIT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "进货保证金\n"
             +"            提货时要检查此加盟商的已进货的金额+本次提货的货物成本不能超过此金额")
    private BigDecimal deposit;

    /**
     * Database Column Remarks:
     *   已占用的进货保证金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.DEPOSIT_USED
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "已占用的进货保证金")
    private BigDecimal depositUsed;

    /**
     * Database Column Remarks:
     *   修改时间戳(添加或更新本条记录时的时间戳)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "修改时间戳(添加或更新本条记录时的时间戳)")
    private Long modifiedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.ID
     *
     * @return the value of AFC_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.ID
     *
     * @param id the value for AFC_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.BALANCE
     *
     * @return the value of AFC_ACCOUNT.BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.BALANCE
     *
     * @param balance the value for AFC_ACCOUNT.BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.SETTLE_BALANCE
     *
     * @return the value of AFC_ACCOUNT.SETTLE_BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getSettleBalance() {
        return settleBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.SETTLE_BALANCE
     *
     * @param settleBalance the value for AFC_ACCOUNT.SETTLE_BALANCE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setSettleBalance(BigDecimal settleBalance) {
        this.settleBalance = settleBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.SETTLE_TIME
     *
     * @return the value of AFC_ACCOUNT.SETTLE_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Date getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.SETTLE_TIME
     *
     * @param settleTime the value for AFC_ACCOUNT.SETTLE_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setSettleTime(Date settleTime) {
        this.settleTime = settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.WITHDRAWING
     *
     * @return the value of AFC_ACCOUNT.WITHDRAWING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getWithdrawing() {
        return withdrawing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.WITHDRAWING
     *
     * @param withdrawing the value for AFC_ACCOUNT.WITHDRAWING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setWithdrawing(BigDecimal withdrawing) {
        this.withdrawing = withdrawing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.CASHBACK
     *
     * @return the value of AFC_ACCOUNT.CASHBACK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getCashback() {
        return cashback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.CASHBACK
     *
     * @param cashback the value for AFC_ACCOUNT.CASHBACK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setCashback(BigDecimal cashback) {
        this.cashback = cashback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.CASHBACKING
     *
     * @return the value of AFC_ACCOUNT.CASHBACKING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getCashbacking() {
        return cashbacking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.CASHBACKING
     *
     * @param cashbacking the value for AFC_ACCOUNT.CASHBACKING
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setCashbacking(BigDecimal cashbacking) {
        this.cashbacking = cashbacking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.DEPOSIT
     *
     * @return the value of AFC_ACCOUNT.DEPOSIT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.DEPOSIT
     *
     * @param deposit the value for AFC_ACCOUNT.DEPOSIT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.DEPOSIT_USED
     *
     * @return the value of AFC_ACCOUNT.DEPOSIT_USED
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getDepositUsed() {
        return depositUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.DEPOSIT_USED
     *
     * @param depositUsed the value for AFC_ACCOUNT.DEPOSIT_USED
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setDepositUsed(BigDecimal depositUsed) {
        this.depositUsed = depositUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @return the value of AFC_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Long getModifiedTimestamp() {
        return modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @param modifiedTimestamp the value for AFC_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setModifiedTimestamp(Long modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", balance=").append(balance);
        sb.append(", settleBalance=").append(settleBalance);
        sb.append(", settleTime=").append(settleTime);
        sb.append(", withdrawing=").append(withdrawing);
        sb.append(", cashback=").append(cashback);
        sb.append(", cashbacking=").append(cashbacking);
        sb.append(", deposit=").append(deposit);
        sb.append(", depositUsed=").append(depositUsed);
        sb.append(", modifiedTimestamp=").append(modifiedTimestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcAccountMo other = (AfcAccountMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}