package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   平台交易
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_PLATFORM_TRADE
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-11 15:01:51
 */
@ApiModel(value = "AfcPlatformTradeMo", description = "平台交易")
@JsonInclude(Include.NON_NULL)
public class AfcPlatformTradeMo implements Serializable {
    /**
     * Database Column Remarks:
     *   平台交易ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "平台交易ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   交易类型（1：收取服务费(购买交易成功)  2：退回服务费(用户退款)）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.PLATFORM_TRADE_TYPE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "交易类型（1：收取服务费(购买交易成功)  2：退回服务费(用户退款)）")
    private Byte platformTradeType;

    /**
     * Database Column Remarks:
     *   销售/退货单ID
     *               流水类型是收取服务费，则填写销售订单ID
     *               如果是退回服务费，则填写退货订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.ORDER_ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "销售/退货单ID\n"
             +"            流水类型是收取服务费，则填写销售订单ID\n"
             +"            如果是退回服务费，则填写退货订单ID")
    private Long orderId;

    /**
     * Database Column Remarks:
     *   变化的金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "变化的金额")
    private BigDecimal changeAmount;

    /**
     * Database Column Remarks:
     *   余额（修改后）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.BALANCE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "余额（修改后）")
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   修改时间戳
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_TRADE.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @ApiModelProperty(value = "修改时间戳")
    private Long modifiedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_PLATFORM_TRADE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.ID
     *
     * @return the value of AFC_PLATFORM_TRADE.ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.ID
     *
     * @param id the value for AFC_PLATFORM_TRADE.ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.PLATFORM_TRADE_TYPE
     *
     * @return the value of AFC_PLATFORM_TRADE.PLATFORM_TRADE_TYPE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public Byte getPlatformTradeType() {
        return platformTradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.PLATFORM_TRADE_TYPE
     *
     * @param platformTradeType the value for AFC_PLATFORM_TRADE.PLATFORM_TRADE_TYPE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setPlatformTradeType(Byte platformTradeType) {
        this.platformTradeType = platformTradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.ORDER_ID
     *
     * @return the value of AFC_PLATFORM_TRADE.ORDER_ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.ORDER_ID
     *
     * @param orderId the value for AFC_PLATFORM_TRADE.ORDER_ID
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.CHANGE_AMOUNT
     *
     * @return the value of AFC_PLATFORM_TRADE.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public BigDecimal getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.CHANGE_AMOUNT
     *
     * @param changeAmount the value for AFC_PLATFORM_TRADE.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.BALANCE
     *
     * @return the value of AFC_PLATFORM_TRADE.BALANCE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.BALANCE
     *
     * @param balance the value for AFC_PLATFORM_TRADE.BALANCE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_TRADE.MODIFIED_TIMESTAMP
     *
     * @return the value of AFC_PLATFORM_TRADE.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public Long getModifiedTimestamp() {
        return modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_TRADE.MODIFIED_TIMESTAMP
     *
     * @param modifiedTimestamp the value for AFC_PLATFORM_TRADE.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    public void setModifiedTimestamp(Long modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_TRADE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", platformTradeType=").append(platformTradeType);
        sb.append(", orderId=").append(orderId);
        sb.append(", changeAmount=").append(changeAmount);
        sb.append(", balance=").append(balance);
        sb.append(", modifiedTimestamp=").append(modifiedTimestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_TRADE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcPlatformTradeMo other = (AfcPlatformTradeMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_TRADE
     *
     * @mbg.generated 2018-05-11 15:01:51
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}