package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   平台流水
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_PLATFORM_FLOW
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-03 13:37:38
 */
@ApiModel(value = "AfcPlatformFlowMo", description = "平台流水")
@JsonInclude(Include.NON_NULL)
public class AfcPlatformFlowMo implements Serializable {
    /**
     * Database Column Remarks:
     *   平台流水ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "平台流水ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   余额（修改后）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "余额（修改后）")
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   销售/退货单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "销售/退货单ID")
    private Long orderId;

    /**
     * Database Column Remarks:
     *   流水类型（1：平台服务费  2：退款）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "流水类型（1：平台服务费  2：退款）")
    private Byte flowType;

    /**
     * Database Column Remarks:
     *   修改金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.MODIFY_AMOUNT
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "修改金额")
    private BigDecimal modifyAmount;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.MODIFIED_TIME
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.ID
     *
     * @return the value of AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.ID
     *
     * @param id the value for AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @return the value of AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @param balance the value for AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @return the value of AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @param orderId the value for AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @return the value of AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public Byte getFlowType() {
        return flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @param flowType the value for AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setFlowType(Byte flowType) {
        this.flowType = flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.MODIFY_AMOUNT
     *
     * @return the value of AFC_PLATFORM_FLOW.MODIFY_AMOUNT
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public BigDecimal getModifyAmount() {
        return modifyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.MODIFY_AMOUNT
     *
     * @param modifyAmount the value for AFC_PLATFORM_FLOW.MODIFY_AMOUNT
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setModifyAmount(BigDecimal modifyAmount) {
        this.modifyAmount = modifyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.MODIFIED_TIME
     *
     * @return the value of AFC_PLATFORM_FLOW.MODIFIED_TIME
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.MODIFIED_TIME
     *
     * @param modifiedTime the value for AFC_PLATFORM_FLOW.MODIFIED_TIME
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", balance=").append(balance);
        sb.append(", orderId=").append(orderId);
        sb.append(", flowType=").append(flowType);
        sb.append(", modifyAmount=").append(modifyAmount);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcPlatformFlowMo other = (AfcPlatformFlowMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-03 13:37:38
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}