package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   平台流水
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_PLATFORM_FLOW
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-10 11:15:22
 */
@ApiModel(value = "AfcPlatformFlowMo", description = "平台流水")
@JsonInclude(Include.NON_NULL)
public class AfcPlatformFlowMo implements Serializable {
    /**
     * Database Column Remarks:
     *   平台流水ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "平台流水ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   流水类型（1：购买交易收取服务费  2：用户退款退回服务费）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "流水类型（1：购买交易收取服务费  2：用户退款退回服务费）")
    private Byte flowType;

    /**
     * Database Column Remarks:
     *   销售/退货单ID
     *               流水类型是收取服务费，则填写销售订单ID
     *               如果是退回服务费，则填写退货订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "销售/退货单ID\n"
             +"            流水类型是收取服务费，则填写销售订单ID\n"
             +"            如果是退回服务费，则填写退货订单ID")
    private Long orderId;

    /**
     * Database Column Remarks:
     *   变化的金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "变化的金额")
    private BigDecimal changeAmount;

    /**
     * Database Column Remarks:
     *   余额（修改后）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "余额（修改后）")
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   修改时间戳
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_PLATFORM_FLOW.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @ApiModelProperty(value = "修改时间戳")
    private Long modifiedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.ID
     *
     * @return the value of AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.ID
     *
     * @param id the value for AFC_PLATFORM_FLOW.ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @return the value of AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public Byte getFlowType() {
        return flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @param flowType the value for AFC_PLATFORM_FLOW.FLOW_TYPE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setFlowType(Byte flowType) {
        this.flowType = flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @return the value of AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @param orderId the value for AFC_PLATFORM_FLOW.ORDER_ID
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.CHANGE_AMOUNT
     *
     * @return the value of AFC_PLATFORM_FLOW.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public BigDecimal getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.CHANGE_AMOUNT
     *
     * @param changeAmount the value for AFC_PLATFORM_FLOW.CHANGE_AMOUNT
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @return the value of AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.BALANCE
     *
     * @param balance the value for AFC_PLATFORM_FLOW.BALANCE
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_PLATFORM_FLOW.MODIFIED_TIMESTAMP
     *
     * @return the value of AFC_PLATFORM_FLOW.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public Long getModifiedTimestamp() {
        return modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_PLATFORM_FLOW.MODIFIED_TIMESTAMP
     *
     * @param modifiedTimestamp the value for AFC_PLATFORM_FLOW.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    public void setModifiedTimestamp(Long modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowType=").append(flowType);
        sb.append(", orderId=").append(orderId);
        sb.append(", changeAmount=").append(changeAmount);
        sb.append(", balance=").append(balance);
        sb.append(", modifiedTimestamp=").append(modifiedTimestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcPlatformFlowMo other = (AfcPlatformFlowMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_PLATFORM_FLOW
     *
     * @mbg.generated 2018-05-10 11:15:22
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}