package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   结算任务
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_SETTLE_TASK
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-26 19:47:00
 */
@ApiModel(value = "AfcSettleTaskMo", description = "结算任务")
@JsonInclude(Include.NON_NULL)
public class AfcSettleTaskMo implements Serializable {
    /**
     * Database Column Remarks:
     *   任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "任务ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   执行状态(-1:取消；0:未执行；1:已执行)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "执行状态(-1:取消；0:未执行；1:已执行)")
    private Byte executeState;

    /**
     * Database Column Remarks:
     *   计划执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "计划执行时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date executePlanTime;

    /**
     * Database Column Remarks:
     *   实际执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "实际执行时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date executeFactTime;

    /**
     * Database Column Remarks:
     *   账户ID(账户ID也就是用户ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "账户ID(账户ID也就是用户ID)")
    private Long accountId;

    /**
     * Database Column Remarks:
     *   结算类型(交易类型中的几种结算类型)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.TRADE_TYPE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "结算类型(交易类型中的几种结算类型)")
    private Byte tradeType;

    /**
     * Database Column Remarks:
     *   交易总额（收入为正数，支出为负数）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.TRADE_AMOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "交易总额（收入为正数，支出为负数）")
    private BigDecimal tradeAmount;

    /**
     * Database Column Remarks:
     *   交易改变金额1，在交易类型是支付时代表返现金改变了多少
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.CHANGE_AMOUNT1
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "交易改变金额1，在交易类型是支付时代表返现金改变了多少")
    private BigDecimal changeAmount1;

    /**
     * Database Column Remarks:
     *   交易改变金额2，在交易类型是支付时代表余额改变了多少
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.CHANGE_AMOUNT2
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "交易改变金额2，在交易类型是支付时代表余额改变了多少")
    private BigDecimal changeAmount2;

    /**
     * Database Column Remarks:
     *   交易标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.TRADE_TITLE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "交易标题")
    private String tradeTitle;

    /**
     * Database Column Remarks:
     *   交易详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.TRADE_DETAIL
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "交易详情")
    private String tradeDetail;

    /**
     * Database Column Remarks:
     *   订单ID(销售订单ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "订单ID(销售订单ID)")
    private String orderId;

    /**
     * Database Column Remarks:
     *   订单详情ID(销售订单详情ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.ORDER_DETAIL_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "订单详情ID(销售订单详情ID)")
    private String orderDetailId;

    /**
     * Database Column Remarks:
     *   MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.MAC
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "MAC地址")
    private String mac;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_SETTLE_TASK.IP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @ApiModelProperty(value = "IP地址")
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_SETTLE_TASK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.ID
     *
     * @return the value of AFC_SETTLE_TASK.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.ID
     *
     * @param id the value for AFC_SETTLE_TASK.ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.EXECUTE_STATE
     *
     * @return the value of AFC_SETTLE_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Byte getExecuteState() {
        return executeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.EXECUTE_STATE
     *
     * @param executeState the value for AFC_SETTLE_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setExecuteState(Byte executeState) {
        this.executeState = executeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.EXECUTE_PLAN_TIME
     *
     * @return the value of AFC_SETTLE_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Date getExecutePlanTime() {
        return executePlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.EXECUTE_PLAN_TIME
     *
     * @param executePlanTime the value for AFC_SETTLE_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setExecutePlanTime(Date executePlanTime) {
        this.executePlanTime = executePlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.EXECUTE_FACT_TIME
     *
     * @return the value of AFC_SETTLE_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Date getExecuteFactTime() {
        return executeFactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.EXECUTE_FACT_TIME
     *
     * @param executeFactTime the value for AFC_SETTLE_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setExecuteFactTime(Date executeFactTime) {
        this.executeFactTime = executeFactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.ACCOUNT_ID
     *
     * @return the value of AFC_SETTLE_TASK.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.ACCOUNT_ID
     *
     * @param accountId the value for AFC_SETTLE_TASK.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.TRADE_TYPE
     *
     * @return the value of AFC_SETTLE_TASK.TRADE_TYPE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public Byte getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.TRADE_TYPE
     *
     * @param tradeType the value for AFC_SETTLE_TASK.TRADE_TYPE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setTradeType(Byte tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.TRADE_AMOUNT
     *
     * @return the value of AFC_SETTLE_TASK.TRADE_AMOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.TRADE_AMOUNT
     *
     * @param tradeAmount the value for AFC_SETTLE_TASK.TRADE_AMOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.CHANGE_AMOUNT1
     *
     * @return the value of AFC_SETTLE_TASK.CHANGE_AMOUNT1
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getChangeAmount1() {
        return changeAmount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.CHANGE_AMOUNT1
     *
     * @param changeAmount1 the value for AFC_SETTLE_TASK.CHANGE_AMOUNT1
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setChangeAmount1(BigDecimal changeAmount1) {
        this.changeAmount1 = changeAmount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.CHANGE_AMOUNT2
     *
     * @return the value of AFC_SETTLE_TASK.CHANGE_AMOUNT2
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public BigDecimal getChangeAmount2() {
        return changeAmount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.CHANGE_AMOUNT2
     *
     * @param changeAmount2 the value for AFC_SETTLE_TASK.CHANGE_AMOUNT2
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setChangeAmount2(BigDecimal changeAmount2) {
        this.changeAmount2 = changeAmount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.TRADE_TITLE
     *
     * @return the value of AFC_SETTLE_TASK.TRADE_TITLE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getTradeTitle() {
        return tradeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.TRADE_TITLE
     *
     * @param tradeTitle the value for AFC_SETTLE_TASK.TRADE_TITLE
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setTradeTitle(String tradeTitle) {
        this.tradeTitle = tradeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.TRADE_DETAIL
     *
     * @return the value of AFC_SETTLE_TASK.TRADE_DETAIL
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getTradeDetail() {
        return tradeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.TRADE_DETAIL
     *
     * @param tradeDetail the value for AFC_SETTLE_TASK.TRADE_DETAIL
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setTradeDetail(String tradeDetail) {
        this.tradeDetail = tradeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.ORDER_ID
     *
     * @return the value of AFC_SETTLE_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.ORDER_ID
     *
     * @param orderId the value for AFC_SETTLE_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.ORDER_DETAIL_ID
     *
     * @return the value of AFC_SETTLE_TASK.ORDER_DETAIL_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.ORDER_DETAIL_ID
     *
     * @param orderDetailId the value for AFC_SETTLE_TASK.ORDER_DETAIL_ID
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.MAC
     *
     * @return the value of AFC_SETTLE_TASK.MAC
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.MAC
     *
     * @param mac the value for AFC_SETTLE_TASK.MAC
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_SETTLE_TASK.IP
     *
     * @return the value of AFC_SETTLE_TASK.IP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_SETTLE_TASK.IP
     *
     * @param ip the value for AFC_SETTLE_TASK.IP
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_SETTLE_TASK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", executeState=").append(executeState);
        sb.append(", executePlanTime=").append(executePlanTime);
        sb.append(", executeFactTime=").append(executeFactTime);
        sb.append(", accountId=").append(accountId);
        sb.append(", tradeType=").append(tradeType);
        sb.append(", tradeAmount=").append(tradeAmount);
        sb.append(", changeAmount1=").append(changeAmount1);
        sb.append(", changeAmount2=").append(changeAmount2);
        sb.append(", tradeTitle=").append(tradeTitle);
        sb.append(", tradeDetail=").append(tradeDetail);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", mac=").append(mac);
        sb.append(", ip=").append(ip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_SETTLE_TASK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcSettleTaskMo other = (AfcSettleTaskMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_SETTLE_TASK
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}