package rebue.afc.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   提现账户
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AFC_WITHDRAW_ACCOUNT
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-17 10:57:31
 */
@ApiModel(value = "AfcWithdrawAccountMo", description = "提现账户")
@JsonInclude(Include.NON_NULL)
public class AfcWithdrawAccountMo implements Serializable {
    /**
     * Database Column Remarks:
     *   提现账户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "提现账户ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   是否默认提现账户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.IS_DEF
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "是否默认提现账户")
    private Boolean isDef;

    /**
     * Database Column Remarks:
     *   账户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "账户ID")
    private Long accountId;

    /**
     * Database Column Remarks:
     *   提现类型(1-银行卡,2-支付宝)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.WITHDRAW_TYPE
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "提现类型(1-银行卡,2-支付宝)")
    private Byte withdrawType;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.CONTACT_TEL
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "联系电话")
    private String contactTel;

    /**
     * Database Column Remarks:
     *   银行账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NO
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "银行账号")
    private String bankAccountNo;

    /**
     * Database Column Remarks:
     *   银行账户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NAME
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "银行账户名称")
    private String bankAccountName;

    /**
     * Database Column Remarks:
     *   开户银行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "开户银行")
    private String openAccountBank;

    /**
     * Database Column Remarks:
     *   操作人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.OP_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "操作人ID")
    private Long opId;

    /**
     * Database Column Remarks:
     *   MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.MAC
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "MAC地址")
    private String mac;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.IP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "IP地址")
    private String ip;

    /**
     * Database Column Remarks:
     *   修改时间戳(添加或更新本条记录时的时间戳)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AFC_WITHDRAW_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @ApiModelProperty(value = "修改时间戳(添加或更新本条记录时的时间戳)")
    private Long modifiedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.ID
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.ID
     *
     * @param id the value for AFC_WITHDRAW_ACCOUNT.ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.IS_DEF
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.IS_DEF
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Boolean getIsDef() {
        return isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.IS_DEF
     *
     * @param isDef the value for AFC_WITHDRAW_ACCOUNT.IS_DEF
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setIsDef(Boolean isDef) {
        this.isDef = isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.ACCOUNT_ID
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.ACCOUNT_ID
     *
     * @param accountId the value for AFC_WITHDRAW_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.WITHDRAW_TYPE
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.WITHDRAW_TYPE
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Byte getWithdrawType() {
        return withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.WITHDRAW_TYPE
     *
     * @param withdrawType the value for AFC_WITHDRAW_ACCOUNT.WITHDRAW_TYPE
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setWithdrawType(Byte withdrawType) {
        this.withdrawType = withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.CONTACT_TEL
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.CONTACT_TEL
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.CONTACT_TEL
     *
     * @param contactTel the value for AFC_WITHDRAW_ACCOUNT.CONTACT_TEL
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NO
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NO
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NO
     *
     * @param bankAccountNo the value for AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NO
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NAME
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NAME
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NAME
     *
     * @param bankAccountName the value for AFC_WITHDRAW_ACCOUNT.BANK_ACCOUNT_NAME
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getOpenAccountBank() {
        return openAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @param openAccountBank the value for AFC_WITHDRAW_ACCOUNT.OPEN_ACCOUNT_BANK
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setOpenAccountBank(String openAccountBank) {
        this.openAccountBank = openAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.OP_ID
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.OP_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.OP_ID
     *
     * @param opId the value for AFC_WITHDRAW_ACCOUNT.OP_ID
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.MAC
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.MAC
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.MAC
     *
     * @param mac the value for AFC_WITHDRAW_ACCOUNT.MAC
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.IP
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.IP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.IP
     *
     * @param ip the value for AFC_WITHDRAW_ACCOUNT.IP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AFC_WITHDRAW_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @return the value of AFC_WITHDRAW_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public Long getModifiedTimestamp() {
        return modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AFC_WITHDRAW_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @param modifiedTimestamp the value for AFC_WITHDRAW_ACCOUNT.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    public void setModifiedTimestamp(Long modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDef=").append(isDef);
        sb.append(", accountId=").append(accountId);
        sb.append(", withdrawType=").append(withdrawType);
        sb.append(", contactTel=").append(contactTel);
        sb.append(", bankAccountNo=").append(bankAccountNo);
        sb.append(", bankAccountName=").append(bankAccountName);
        sb.append(", openAccountBank=").append(openAccountBank);
        sb.append(", opId=").append(opId);
        sb.append(", mac=").append(mac);
        sb.append(", ip=").append(ip);
        sb.append(", modifiedTimestamp=").append(modifiedTimestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfcWithdrawAccountMo other = (AfcWithdrawAccountMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-17 10:57:31
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}