package rebue.afc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.afc.mo.AfcPlatformMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import java.math.BigDecimal;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface AfcPlatformMapper
		extends
			MybatisBaseMapper<AfcPlatformMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	int insert(AfcPlatformMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	int insertSelective(AfcPlatformMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	AfcPlatformMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	int updateByPrimaryKeySelective(AfcPlatformMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	int updateByPrimaryKey(AfcPlatformMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	List<AfcPlatformMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	List<AfcPlatformMo> selectSelective(AfcPlatformMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PLATFORM
	 *
	 * @mbg.generated 2018-05-15 15:43:27
	 */
	boolean existSelective(AfcPlatformMo record);

	/**
	 * 修改平台余额
	 * 
	 * @param newBalance
	 *            修改后的余额
	 * @param newModifiedTimestamp
	 *            修改的时间戳
	 * @param oldModifiedTimestamp
	 *            旧的修改时间(用来防止并发修改)
	 * @param id
	 *            要修改的平台的ID
	 */
	@Update("update AFC_PLATFORM set BALANCE=#{newBalance},MODIFIED_TIMESTAMP=#{newModifiedTimestamp} "
			+ "where ID=#{id} and BALANCE=#{oldBalance} and MODIFIED_TIMESTAMP=#{oldModifiedTimestamp}")
	int modifyBalance(@Param("newBalance") BigDecimal newBalance,
			@Param("newModifiedTimestamp") Long newModifiedTimestamp,
			@Param("oldBalance") BigDecimal oldBalance,
			@Param("oldModifiedTimestamp") Long oldModifiedTimestamp,
			@Param("id") Long id);
}