package rebue.afc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.afc.mo.AfcPayMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AfcPayMapper extends MybatisBaseMapper<AfcPayMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	int insert(AfcPayMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	int insertSelective(AfcPayMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	AfcPayMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	int updateByPrimaryKeySelective(AfcPayMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	int updateByPrimaryKey(AfcPayMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	List<AfcPayMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	List<AfcPayMo> selectSelective(AfcPayMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AFC_PAY
	 *
	 * @mbg.generated 2018-05-04 10:12:37
	 */
	boolean existSelective(AfcPayMo record);

	/**
	 */
	public AfcPayMo selectByPayTypeAndOrderId(
			@Param("payTypeId") Integer payTypeId,
			@Param("orderId") String orderId);
}