package rebue.afc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.afc.mo.AfcWithdrawAccountMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface AfcWithdrawAccountMapper extends MybatisBaseMapper<AfcWithdrawAccountMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    int insert(AfcWithdrawAccountMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    int insertSelective(AfcWithdrawAccountMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    AfcWithdrawAccountMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    int updateByPrimaryKeySelective(AfcWithdrawAccountMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    int updateByPrimaryKey(AfcWithdrawAccountMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    List<AfcWithdrawAccountMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    List<AfcWithdrawAccountMo> selectSelective(AfcWithdrawAccountMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW_ACCOUNT
     *
     * @mbg.generated 2018-05-26 19:47:00
     */
    boolean existSelective(AfcWithdrawAccountMo record);
}