package rebue.afc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.afc.mo.AfcWithdrawMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface AfcWithdrawMapper extends MybatisBaseMapper<AfcWithdrawMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    int insert(AfcWithdrawMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    int insertSelective(AfcWithdrawMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    AfcWithdrawMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    int updateByPrimaryKeySelective(AfcWithdrawMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    int updateByPrimaryKey(AfcWithdrawMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    List<AfcWithdrawMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    List<AfcWithdrawMo> selectSelective(AfcWithdrawMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFC_WITHDRAW
     *
     * @mbg.generated 2018-05-10 15:25:05
     */
    boolean existSelective(AfcWithdrawMo record);
}