package rebue.afc.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import rebue.afc.mo.VpayTradeTaskMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface VpayTradeTaskMapper extends MybatisBaseMapper<VpayTradeTaskMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    int insert(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    int insertSelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    VpayTradeTaskMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    int updateByPrimaryKeySelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    int updateByPrimaryKey(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    List<VpayTradeTaskMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    List<VpayTradeTaskMo> selectSelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 16:22:34
     */
    boolean existSelective(VpayTradeTaskMo record);

    /**
     * 获取计划执行时间在当前时间之前的任务列表
     */
    List<VpayTradeTaskMo> selectByExecutePlanTimeBeforeNow();
}