package rebue.afc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.afc.mo.VpayTradeTaskMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface VpayTradeTaskMapper extends MybatisBaseMapper<VpayTradeTaskMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    int insert(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    int insertSelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    VpayTradeTaskMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    int updateByPrimaryKeySelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    int updateByPrimaryKey(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    List<VpayTradeTaskMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    List<VpayTradeTaskMo> selectSelective(VpayTradeTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VPAY_TRADE_TASK
     *
     * @mbg.generated 2018-05-04 10:12:18
     */
    boolean existSelective(VpayTradeTaskMo record);
}